# Version of the configuration file
version: 3.0.0
# 主题颜色 "default" or "cyberpunk"
variant: default
# logo
logo: /img/logo.svg
# Page metadata configurations
language: zh-CN
head:
    open_graph:
        # 页面标题 (og:title) (可选)
        # 大部分情况下请留空
        title:
        # 页面类型 (og:type) (可选)
        # 大部分情况下请留空
        type: blog
        # 页面URL地址 (og:url) (可选)
        # 大部分情况下请留空
        url:
        # 页面封面图 (og:image) (可选)
        # 大部分情况下请留空
        image:
        # 站点名称 (og:site_name) (可选)
        # 大部分情况下请留空
        site_name:
        # 页面作者 (article:author) (可选)
        # 大部分情况下请留空
        author:
        # 页面描述 (og:description) (可选)
        # 大部分情况下请留空
        description:
# Page top navigation bar configurations
navbar:
    # 这里是导航
    menu:
        首页: /
        文章: /archives
        分类: /categories
        标签: /tags
        #  这个特殊 找的是跟目录下的一个source > production 其余的是 当前目录layout- >
        作品集: /production
        关于我: /about
    # 导航右侧图标和链接
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/A-lyc'
# 页脚底部的信息
footer:
    # icon 右侧图标和链接
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ppoffice/hexo-theme-icarus'
# 文章相关的配置
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # 显示赋值代码
        clipboard: true
        # 是否默认展开 "folded（不展开）", "unfolded"
        fold: folded
    # 是否为每一篇文章显示缩略图
    thumbnail: true
    # 是否显示估计的文章阅读时间
    readtime: false
# 搜索插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight

# 评论插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
#comment:
#    type: disqus
#    # Disqus shortname
#    shortname: ''

# 捐赠插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donates:
    # 支付宝捐赠按钮配置
    -
        type: alipay
        # Alipay qrcode image URL
        qrcode: ''

    # 给我买杯咖啡”捐赠按钮配置
    -
        type: buymeacoffee
        # URL到“给我买杯咖啡”页面
        url: ''

    # Patreon捐赠按钮配置
    -
        type: patreon
        # 到Patreon页面的URL
        url: ''

    # 微信捐赠按钮配置
    -
        type: wechat
        # 微信qrcode图像URL
        qrcode: ''

# 侧边栏的配置。
# 请注意，一个侧边栏只有在它至少有一个小部件时才可见
sidebar:
    # 左栏的配置
    left:
        # 当页面滚动时，侧边栏是否贴在顶部
        sticky: false
    # 右栏的配置
    right:
        #当页面滚动时，侧边栏是否贴在顶部
        sticky: true
# 侧栏小部件的配置
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # 配置小部件的配置
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: left
        type: profile
        # 作者卡；著者卡片
        author: 李勇超
        # 作者的标题
        author_title: 821328978@qq.com
        # 作者的当前位置
        location: 山东省滨州市
        # 头像图像的URL或路径
        avatar: 
        # 是否显示圆角头像图像
        avatar_rounded: false
        # Gravatar的电子邮件地址
        gravatar: 
        # follow按钮的URL或路径
        follow_link: 'https://github.com/A-lyc'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/A-lyc'
            Facebook:
                icon: fab fa-facebook
                url: 'https://facebook.com'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com'
            Dribbble:
                icon: fab fa-dribbble
                url: 'https://dribbble.com'
            RSS:
                icon: fas fa-rss
                url: /
    # 小部件配置的目录
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: right
        type: toc
    # 推荐链接小部件配置

    # 归档
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: left
        type: archives

    #最新文章
    -
        #小部件应该放在哪里，左边栏还是右边栏
        position: left
        type: recent_posts

    # 分类
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: right
        type: categories

    # 标签
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: left
        type: tags

    # 谷歌FeedBurner电子邮件订阅部件配置
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: left
        type: subscribe_email
        # Hint text under the email input
        description: 
        # Feedburner ID
        feedburner_id: ''

# 插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # 启用页面启动动画
    animejs: true
    # 显示“回到顶部”按钮
    back_to_top: true
    # 显示“百度分析插件设置返回到顶部按钮”
    # https://tongji.baidu.com
    baidu_analytics:
        # 百度分析跟踪ID
        tracking_id: 
    # BuSuanZi网站/页面查看计数器
    # https://busuanzi.ibruce.info
    busuanzi: false
    # CNZZ统计
    # https://www.umeng.com/web
    cnzz:
        # CNZZ tracker id
        id: 
        # CNZZ website id
        web_id: 
    # 启用lightGallery和正规化图库插件
    gallery: true
    # 谷歌分析插件设置
    # https://analytics.google.com
    google_analytics:
        # Google Analytics tracking ID
        tracking_id: 
    # Hotjar用户反馈插件
    # https://www.hotjar.com/
    hotjar:
        # Hotjar site id
        site_id: 
    # 启用KaTeX数学排版支持
    # https://katex.org/
    katex: false
    # Enable the MathJax math typesetting support
    # https://www.mathjax.org/
    mathjax: false
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated_browser: false
    # Show a progress bar at top of the page on page loading
    progressbar: true
# CDN提供商设置
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # 名称或URL模板的JavaScript和/或样式表CDN提供
    cdn: jsdelivr
    # 名称或网址模板的webfont CDN提供
    fontcdn: google
    # 名称或URL的fontawesome图标字体CDN提供
    iconcdn: fontawesome
